package com.janboerman.starhunt.generator

val PluginHubProject = "PluginHub-Project"
val PluginProject = "RuneLite-Plugin"
val CommonProject = "Common";

@main def generate(): Unit = {

    val rootDir = os.pwd
    if (!rootDir.endsWith(os.RelPath("F2P-StarHunt"))) {
        println("Please run this script from root directory (F2P-StarHunt)")
        return
    }

    val pluginDir = rootDir/PluginProject
    val commonDir = rootDir/CommonProject
    val gradleProjectDir = rootDir/PluginHubProject

    os.proc("git", "clone", "https://github.com/runelite/example-plugin.git", PluginHubProject).call(rootDir)
    os.remove.all(gradleProjectDir/"src"/"test"/"java"/"com")
    os.remove.all(gradleProjectDir/"src"/"main"/"java"/"com")

    val pluginSrc = pluginDir/"src"
    val commonSrc = commonDir/"src"
    val targetSrc = gradleProjectDir/"src"
    os.copy(from = commonSrc, to = targetSrc, mergeFolders = true)
    os.copy(from = pluginSrc, to = targetSrc, mergeFolders = true)

    val targetReadMe = gradleProjectDir/"README.md"
    os.copy(rootDir/"README.md", targetReadMe, replaceExisting = true)
    os.write.append(targetReadMe,
        """
          |
          |# This is a generated project
          |This project has been generated by the PluginHub-Project-Generator over at [F2P-StarHunt](https://github.com/Jannyboy11/F2P-StarHunt).
          |""".stripMargin)

}

@main def push(): Unit = {

    val rootDir = os.pwd
    if (!rootDir.endsWith(os.RelPath("F2P-StarHunt"))) {
        println("Please run this script from root directory (F2P-StarHunt)")
        return
    }

    val gradleProjectDir = rootDir/PluginHubProject
    os.proc("git", "add", ".").call(gradleProjectDir)
    os.proc("git", "commit", "-m", "\"generated commit\"").call(gradleProjectDir)
    os.proc("git", "branch", "-M", "master").call(gradleProjectDir)
    os.proc("git", "remote", "add", "f2p-starhunt", "git@github.com:Jannyboy11/F2P-StarHunt-PluginHub.git").call(gradleProjectDir)
    os.proc("git", "push", "--set-upstream", "f2p-starhunt", "master").call(gradleProjectDir)

}
