package com.janboerman.starhunt;

public enum StarLocation {

    WILDY_RUNITE_ROCKS,
    WILDY_CENTRE_MINE,
    WILDY_SOUTH_WEST_MINE,
    WILDY_SOUTH_MINE,

    DWARVEN_MINE_ENTRANCE,
    MINING_GUILD_ENTRANCE,
    CRAFTING_GUILD,
    RIMMINGTON_MINE,

    DRAYNOR_VILLAGE_BANK,
    LUMBRIDGE_SWAMP_SOUTH_WEST_MINE,
    LUMBRIDGE_SWAMP_SOUTH_EAST_MINE,

    VARROCK_SOUTH_WEST_MINE,
    VARROCK_SOUTH_EAST_MINE,
    VARROCK_AUBURY,

    AL_KHARID_MINE,
    DUELLING_ARENA,
    AL_KHARID_BANK,

    CORSAIR_COVE_BANK,
    CORSAIR_COVE_RESOURCE_AREA;

    //TODO WorldPoints :)

}
