package com.janboerman.starhunt.common;

public enum StarLocation {

    WILDY_RUNITE_ROCKS,
    WILDY_CENTRE_MINE,
    WILDY_SOUTH_WEST_MINE,
    WILDY_SOUTH_MINE,

    DWARVEN_MINE,
    MINING_GUILD,
    CRAFTING_GUILD,
    RIMMINGTON_MINE,

    DRAYNOR_VILLAGE_BANK,
    LUMBRIDGE_SWAMP_SOUTH_WEST_MINE,
    LUMBRIDGE_SWAMP_SOUTH_EAST_MINE,

    VARROCK_SOUTH_WEST_MINE,
    VARROCK_SOUTH_EAST_MINE,
    VARROCK_AUBURY,

    AL_KHARID_MINE,
    AL_KHARID_BANK,
    DUELLING_ARENA,

    CORSAIR_COVE_BANK,
    CORSAIR_COVE_RESOURCE_AREA;

}
